### ISSUE TITLE
[BUG] Signals stop working with extern crate and git dependency

### ISSUE THREAD

**Issue by nphias** [holochain/holochain#2418]
**Describe the bug**
I noticed that when using local zome code to compile to wasm, signals from the conductor work fine.
However when I use `extern crate hc_zome_name` where the dependency is a github repo, signals no longer work.
(callzome works fine).    Same result when using tryorama or the javascript hc-client. 

in my cargo.toml :
 
```
[dependencies]
hc_myzome_dna = {git = "https://github.com/example/zome_code.git", branch = "main"} 
```

**Expected behavior**
signals arrive though the websocket to the front-end 

**System information:**
 - OS: [mac]
- holochain 0.1.4
- build info: 
{"git_info":null,"cargo_pkg_version":"0.1.4","hdk_version_req":"0.1.2","hdi_version_req":"0.2.2","timestamp":"2023-05-15T19:51:12.161653Z","hostname":"MacBook-Pro-3.local","host":"aarch64-apple-darwin","target":"aarch64-apple-darwin","rustc_version":"rustc 1.66.1 (90743e729 2023-01-10)","rustflags":"","profile":"release"}

**Comment by ThetaSinner** [comment]
@nphias do you already have a project/branch with a reproduction that you could share?

**Comment by nphias** [comment]
> 

working on a clean one now

**Comment by ThetaSinner** [comment]
Thank you @nphias, this is on my list to look at

**Comment by ThetaSinner** [comment]
Confirming the reproduction looks good. Thank you for that!

I'm not sure right now when this will get looked at but it definitely seems worth trying to trace down

**Comment by nphias** [comment]
problem continues with holochain version 0.1.5

**Comment by ThetaSinner** [comment]
Okay, I have good news on this because I think I have it figured out. The `extern crate` vs. 'copy the code' approaches do yield different WASMs which I cannot explain but what I can say is that either way you get the exact same functions exposed and they do the same thing. Maybe somebody who knows more about the details of how Rust code gets transformed into WASM could explain the difference but I don't think it actually matters a great deal here.

What is much more important is that integrity zomes are strictly excluded from signalling. That isn't something I was looking for exactly but it's quite evident from the Holochain code once you dig deep enough trying to trace what the conductor is doing. So that led me to looking at where the signals are being sent from. The `invitations` zome that does the signalling is being loaded as an integrity zome and the integrity zome isn't being loaded at all.

@nphias Could you update your `workdir/dna/dna.yaml` to look like this:

```yaml
---
manifest_version: "1"
name: group
integrity:
  network_seed: ~
  properties: ~
  origin_time: 1669136217555883
  zomes:
    - name: profiles_integrity
      hash: ~
      bundled: "../../target/wasm32-unknown-unknown/release/profiles_integrity.wasm"
      dependencies: ~
    - name: invitations_integrity
      hash: ~
      bundled: "../../target/wasm32-unknown-unknown/release/invitations_integrity.wasm"
      dependencies: ~
coordinator:
  zomes:
    - name: profiles
      bundled: "../../target/wasm32-unknown-unknown/release/profiles.wasm"
      dependencies:
        - name: profiles_integrity
    - name: invitations
      bundled: "../../target/wasm32-unknown-unknown/release/invitations.wasm"
      dependencies:
        - name: invitations_integrity
```

and re-run the tests? I believe this is enough to address the problem. I am seeing test `4.` fail, but it doesn't appear to be related to signals so I'll hold off looking at that unless something else is happening unexpectedly there.

**Comment by nphias** [comment]
Thanks ThetaSinner,

So it seems it was a problem with my dna.yaml file which i fixed .. mentioning both coordinator and integrity zomes and using correct indentation .  The outcome of this enquiry might be that it would be better to have a warning if not all zomes are referenced in the yaml file.. maybe a parser for the yaml..  some useful error/warning messages instead of silent failure

**Comment by ThetaSinner** [comment]
Thanks @nphias, I've opened #2710 to catch DNA manifest errors which I think can quickly be done with [this](https://serde.rs/container-attrs.html#deny_unknown_fields).

I've also opened an internal ticket to look at rejecting HDK calls from integrity zomes because that can still happen with a valid manifest.
